name: composite-input-output-test-example
on:
  workflow_dispatch:

jobs:
  composite-input-output-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: capturing-step-id
        uses: ./.github/actions/hello-input-output
        with:
          who-to-greet: 'Santa'
      - name: 'Show The Output'
        run: echo ${{ steps.capturing-step-id.outputs.random-number }}