name: 'Project C'

on:
  push:
    paths:
      - "Project-C/**"

jobs:
  project-c:
    uses: comdotlinux/composite-actions-example/.github/workflows/workflow-call-example.yaml@main
    with:
      project: Project-C
      git-ref: ${{ github.sha }}
    secrets:
      boo: 'scooby dooby doooooooo'
