name: 'Project D'

on:
  push:
    paths:
      - "Project-D/**"

jobs:
  project-d:
    uses: comdotlinux/composite-actions-example/.github/workflows/workflow-call-example.yaml@main
    with:
      project: Project-D
      git-ref: ${{ github.sha }}
    secrets:
      boo: 'scooby dooby dooooooooooooooooooo'
